version: '3'

services:

  mongo:
    build:
      context: .
      dockerfile: newmongo.dockerfile
    ports:
      - "27017:27017"
    volumes:
      - /Users/nmserver/dockering-app/Project-Wiki/dump:/usr/data/db/dump
    environment:
      MONGO_DATA_DIR: /data/db/dump
      DB_NAME: Discography
      DB_USER: battle
      DB_PASS: studies
      MONGO_INITDB_ROOT_USERNAME: battle
      MONGO_INITDB_ROOT_PASSWORD: studies

  your-app:
    build:
      context: .
      dockerfile: app.dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/yourdatabase"

