version: '3'

services:
  mongo:
    build:
      context: .
      dockerfile: mongo.dockerfile
    ports:
      - "27017:27017"
    volumes:
      - /Users/nmserver/dockering-app/Project-Wiki/dump:/usr/data/db/dump
    networks:
      - pw-network
    environment:
      MONGO_DATA_DIR: /data/db/dump
      DB_NAME: admin

  project-wiki:
    build:
      context: .
      dockerfile: app.dockerfile
    networks:
      - pw-network
    ports:
      - "31415:31415"
    depends_on:
      - mongo
    environment:
      MONGO_DATA_DIR: /data/db/dump
      DB_SERVICE: mongo
      DB_NAME: admin
      DB_USER: battle
      DB_PASS: studies

networks:
  pw-network:
    driver: bridge

