version: '3'

services:
  mongo:
    build:
      context: .
      dockerfile: mongo.dockerfile
    ports:
      - "27017:27017"
    volumes:
      - /Users/nmserver/dockering-app/Project-Wiki/dump:/usr/src/app/dump
    environment:
      MONGO_DATA_DIR: /data/db

  your-app:
    build:
      context: .
      dockerfile: app.dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/yourdatabase"

