version: '3'

services:
  mongo:
    build:
      context: .
      dockerfile: mongo.dockerfile
    ports:
      - "27017:27017"
    volumes:
      - /Users/nmserver/RobinsFeb8ProjectWiki/dockering-pw/dump:/data/db/dump
    networks:
      - pw-network
    environment:
      MONGO_DATA_DIR: /data/db/dump

  project-wiki:
    build:
      context: .
      dockerfile: app.dockerfile
    networks:
      - pw-network
    ports:
      - "31415:31415"
    depends_on:
      - mongo
    volumes:
      - /Users/nmserver/RobinsFeb8ProjectWiki/Project_Wiki_Data/uploads:/app/uploads
    environment:
      MONGO_DATA_DIR: /data/db/dump
      DB_SERVICE: mongo

networks:
  pw-network:
    driver: bridge

